/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import code.ReadCSV;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import data.LoadData;
import db.db;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class ImportData extends javax.swing.JPanel {

    /**
     * Creates new form importData
     */
    public ImportData() {
        initComponents();
    }
    
    private List<ReadCSV> loadedData;
    
    private void loadCSV() {
    
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
    
        if (result == fileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = LoadData.loadcsv(selectedFile);
            displayDataInTable(loadedData);
        }
    }
    
    private void displayDataInTable(List<ReadCSV> dataList) {
        
        DefaultTableModel model = (DefaultTableModel) TransactionTbl.getModel();
        model.setRowCount(0);
        
        for(int i = 0; i < dataList.size(); i++){
            ReadCSV row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getCus_id(),
                row.getPro_id(),
                row.getPro_name(),
                row.getQty(),
                row.getPer_unit(),
                row.getDate(),
                row.getTotal_price(),
                row.getRegion()
            });
        }
        
    }

    public void saveData() {
        
        int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to upload this data to the database?","Confirm Upload",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Upload canceled.");
            return;
        }
        
        try {
            Connection con = db.getConnection();
            con.setAutoCommit(false);
            String query = "INSERT INTO transactions (tra_id, cus_id, pro_id, pro_name, qty, per_unit, date, total_price, region) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);

            DefaultTableModel model = (DefaultTableModel) TransactionTbl.getModel();
            double total = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                int tra_id = Integer.parseInt(model.getValueAt(i, 0).toString());
                int c_id = Integer.parseInt(model.getValueAt(i, 1).toString());
                int p_id = Integer.parseInt(model.getValueAt(i, 2).toString());
                String p_name = model.getValueAt(i, 3).toString();
                int quantity = Integer.parseInt(model.getValueAt(i, 4).toString());
                double p_unit = Double.parseDouble(model.getValueAt(i, 5).toString());
                String date = model.getValueAt(i, 6).toString();
                double price = Double.parseDouble(model.getValueAt(i, 7).toString());
                String region = model.getValueAt(i, 8).toString();

                total += price;

                pst.setInt(1, tra_id);
                pst.setInt(2, c_id);
                pst.setInt(3, p_id);
                pst.setString(4, p_name);
                pst.setInt(5, quantity);
                pst.setDouble(6, p_unit);
                pst.setString(7, date);
                pst.setDouble(8, price);
                pst.setString(9, region);

                pst.addBatch();
            }

            pst.executeBatch();
            con.commit();

            JOptionPane.showMessageDialog(null, "Data saved successfully!");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        syncBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransactionTbl = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 34, 98));
        jLabel5.setText("Data Import & Management  ");

        uploadBtn.setBackground(new java.awt.Color(13, 42, 171));
        uploadBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        uploadBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadBtn.setText("Upload CSV");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        syncBtn.setBackground(new java.awt.Color(215, 223, 255));
        syncBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 17)); // NOI18N
        syncBtn.setText("Sync with Database");
        syncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncBtnActionPerformed(evt);
            }
        });

        TransactionTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Customer ID", "Production ID", "Product Name", "Quantity", "Price per unit", "Date", "Total Price", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TransactionTbl);
        if (TransactionTbl.getColumnModel().getColumnCount() > 0) {
            TransactionTbl.getColumnModel().getColumn(0).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(1).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(2).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(3).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(4).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(5).setResizable(false);
            TransactionTbl.getColumnModel().getColumn(6).setResizable(false);
        }

        printBtn.setBackground(new java.awt.Color(215, 223, 255));
        printBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 17)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(syncBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(syncBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // TODO add your handling code here:
        loadCSV();
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void syncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncBtnActionPerformed
        saveData();
    }//GEN-LAST:event_syncBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        
        try {
            boolean complete = TransactionTbl.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Datas"), new MessageFormat("Page {0}"));
            
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e){
            JOptionPane.showMessageDialog(null, 0);
        }
        
    }//GEN-LAST:event_printBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TransactionTbl;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton syncBtn;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
