package ui;

import com.formdev.flatlaf.FlatLightLaf;
import db.db;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author bathi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setSize(850, 600);
        setLocationRelativeTo(null);
        //jPanel2.setBorder(new RoundedBorder(25, new java.awt.Color(0, 125, 255), 2));
        //this.setExtendedState(login.MAXIMIZED_BOTH);
    }

    JpanelLoader jpload = new JpanelLoader();

    public void creadentialsCheck() {

        String username = txtUsername.getText();
        String accesscode = txtPassword.getText();

        if (username == null || accesscode == null) {
            JOptionPane.showMessageDialog(this, "Please enter your name and password", "Login Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;
        PreparedStatement pst = null;
        java.sql.ResultSet rs = null;

        try {
            con = db.getConnection();

            String query = "SELECT role, access_code FROM user WHERE user_name = ?";
            pst = con.prepareStatement(query);
            pst.setString(1, username);
            rs = pst.executeQuery();

            if (rs.next()) {

                String dbAccessCode = rs.getString("access_code");
                String role = rs.getString("role");

                //System.out.println(role);
                if (accesscode.equals(dbAccessCode)) {

                    switch (role.toLowerCase()) {
                        case "admin":
                            AdminDashboard dashboard1 = new AdminDashboard();
                            dashboard1.setVisible(true);
                            this.dispose();
                            break;
                        case "manager":
                            ManagerDashboard dashboard2 = new ManagerDashboard();
                            dashboard2.setVisible(true);
                            this.dispose();
                            break;
                        default:
                            JOptionPane.showMessageDialog(this, "Unauthorized role");
                            break;
                    }

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-bg-1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 590);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 34, 98));
        jLabel5.setText("Sampath Food City");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 70, 320, 50);

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel6.setText("Sales Data Analysis System");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 110, 250, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(60, 150, 350, 20);

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 17)); // NOI18N
        jLabel7.setText("Username");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 180, 250, 30);

        txtUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(60, 210, 350, 40);

        jLabel8.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 17)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 260, 250, 30);

        txtPassword.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(60, 290, 350, 40);

        btnLogin.setBackground(new java.awt.Color(1, 34, 98));
        btnLogin.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(60, 370, 350, 40);

        btnClear.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 51, 102));
        btnClear.setText("Clear");
        btnClear.setToolTipText("");
        jPanel2.add(btnClear);
        btnClear.setBounds(60, 420, 350, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 0, 550, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        creadentialsCheck();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatLightLaf.setup(); // You can change to FlatDarkLaf, etc.
            // Optional: customize a few UI properties
            javax.swing.UIManager.put("Button.arc", 20);
            javax.swing.UIManager.put("Component.focusWidth", 1);
            javax.swing.UIManager.put("TextComponent.arc", 15);
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
